
contentDir: "content"
outputDir: "generated"
templatesDir: "templates"
siteTitle: "Tod and Lorna .com"
siteAddress: "https://todandlorna.com/"
descending: True,
defaultExtension: ".html"
startPage: "index.html"
pageConfig:
    pageTitle: "Tod and Lorna .com"
    pageDefaultTemplate: "page.jinja2"
blogConfig:
    title: "Death and Lor"
    blogBaseDir: "tnlblog"
    blogTemplate: "blog.jinja2"
    listingTemplate: "listing.jinja2"
    listingPaginationNum: 5
    listingKeysNeeded: ['hook']
    atomFeeds: True
    tagsTemplate: "tags.jinja2"
    tagTemplate: "tag.jinja2"
    tagPaginationNum: 5
    authorsTemplate: "authors.jinja2"
    authorTemplate: "author.jinja2"
    authorPaginationNum: 10
