name: build-test
description: "Verify the Docker image builds successfully on PR"
triggers:
  events:
    - pull_request_opened
    - pull_request_updated
  branches:
    - main
job:
  image: 10.16.0.1:5000/public/reactorcide/runnerbase:dev
  command: "bash /job/src/.reactorcide/jobs/scripts/build-test.sh"
  timeout: 900
  capabilities:
    - docker
