name: build-and-deploy
description: "Build Docker image and deploy to Kubernetes via Helm"
triggers:
  events:
    - push
  branches:
    - main
paths:
  include: ["content/extra_files/VERSION.txt"]
job:
  image: 10.16.0.1:5000/public/reactorcide/runnerbase:dev
  command: "bash /job/src/.reactorcide/jobs/scripts/build-and-deploy.sh"
  timeout: 1800
  capabilities:
    - docker
environment:
  REGISTRY_INTERNAL: "10.16.0.1:5000"
  REGISTRY_INTERNAL_PATH: "private/todpunk/tnl-site"
  REGISTRY_EXTERNAL: "containers.catalystsquad.com"
  REGISTRY_USER: "${secret:tnl-site/registry:user}"
  REGISTRY_PASSWORD: "${secret:tnl-site/registry:password}"
  KUBECONFIG_CONTENT: "${secret:tnl-site/k8s:kubeconfig}"
  K8S_NAMESPACE: "tnl-site"
  HELM_RELEASE: "tnl-site"
  HELM_CHART: "catalyst-helm/pysocha-site"
  HELM_CHART_VERSION: "1.1.1"
