name: Pull Request
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - .github/
jobs:
  version-and-push:
    name: Version and Push
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTOMATION_PAT }}
          fetch-depth: 0
          ref: '${{ steps.extract_branch.outputs.branch }}'
      - name: setup git config
        run: |
          git config --global user.name "Tod Hansmann (automation)"
          git config --global user.email "<githubpub@todandlorna.com>"
      - name: Get semver-tags
        run: |
          wget -c https://github.com/catalystsquad/semver-tags/releases/download/v0.3.3/semver-tags.tar.gz -O - | tar -xz
      - name: Semver Tags Run
        id: semver-tags
        run: |
          ./.github/scripts/do-image-release.sh fullrun
      - if: steps.semver-tags.outputs.RELEASED_CHANGES == 'true'
        name: Build and push image to CS Containers
        shell: bash
        run: |
          echo "${{ secrets.CONTAINERS_AUTH_PW }}" | docker login --username ${{ secrets.CONTAINERS_AUTH_USER }} --password-stdin https://containers.catalystsquad.com
          docker build . -t containers.catalystsquad.com/tnl-site:latest -t containers.catalystsquad.com/tnl-site:${{ steps.semver-tags.outputs.NEW_VERSION }}
          docker image push --all-tags containers.catalystsquad.com/tnl-site
